source 'http://rubygems.org'

gem 'cucumber'
gem 'dotenv'
gem 'ffaker'
gem 'gmail'
gem 'pry'
gem 'rake'
gem 'reek'
gem 'require_all'
gem 'rest-client'
gem 'rspec-expectations'
gem 'rubocop', require: false
gem 'rubocop-rspec'
gem 'rubocop-rails'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'uuid'
gem 'airborne'